name: 'Terraform apply'
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: write
jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials for S3 state file access
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: arn:aws:iam::715102664058:role/GithubTerraformRole
          aws-region: eu-west-2
          role-session-name: TerraformRole
      - name: Terraform apply
        run: |
          terraform init
          terraform apply --auto-approve
